### PR TITLE
Support arrays that have non-numbers as well.

### PR DESCRIPTION
**Pull request by icyflame**
Signed-off-by: Siddharth Kannan kannan.siddharth12@gmail.com

### CODE REVIEW

**Comment by arthurvr** [comment]
Why? What's your use-case? I'd say this should happen on the user side, this way seems like a source of confusion.

**Comment by kevva** [comment]
Yeah, why would want to supply a random array?

**Comment by icyflame** [comment]
I don't have a specific use-case, but seemed like a good thing to have. (It's there in [array-sum](https://www.npmjs.com/package/array-sum) )

I guess it's not really necessary. Sorry!

**Comment by arthurvr** [comment]
No worries, thanks for the suggestion. 

> (It's there in array-sum )

That's one of the reasons I always use https://www.npmjs.com/package/math-sum :p

**Pull request closed without merging**
